// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dictionaries.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DictionariesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionariesRequest) Reset()         { *m = DictionariesRequest{} }
func (m *DictionariesRequest) String() string { return proto.CompactTextString(m) }
func (*DictionariesRequest) ProtoMessage()    {}
func (*DictionariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48bb302865fe9053, []int{0}
}

func (m *DictionariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionariesRequest.Unmarshal(m, b)
}
func (m *DictionariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionariesRequest.Marshal(b, m, deterministic)
}
func (m *DictionariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionariesRequest.Merge(m, src)
}
func (m *DictionariesRequest) XXX_Size() int {
	return xxx_messageInfo_DictionariesRequest.Size(m)
}
func (m *DictionariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DictionariesRequest proto.InternalMessageInfo

type Dictionary struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dictionary) Reset()         { *m = Dictionary{} }
func (m *Dictionary) String() string { return proto.CompactTextString(m) }
func (*Dictionary) ProtoMessage()    {}
func (*Dictionary) Descriptor() ([]byte, []int) {
	return fileDescriptor_48bb302865fe9053, []int{1}
}

func (m *Dictionary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dictionary.Unmarshal(m, b)
}
func (m *Dictionary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dictionary.Marshal(b, m, deterministic)
}
func (m *Dictionary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dictionary.Merge(m, src)
}
func (m *Dictionary) XXX_Size() int {
	return xxx_messageInfo_Dictionary.Size(m)
}
func (m *Dictionary) XXX_DiscardUnknown() {
	xxx_messageInfo_Dictionary.DiscardUnknown(m)
}

var xxx_messageInfo_Dictionary proto.InternalMessageInfo

func (m *Dictionary) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Dictionary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DictionariesResponse struct {
	ComplicationLevels   []*Dictionary `protobuf:"bytes,1,rep,name=complication_levels,json=complicationLevels,proto3" json:"complication_levels,omitempty"`
	FortressLevels       []*Dictionary `protobuf:"bytes,2,rep,name=fortress_levels,json=fortressLevels,proto3" json:"fortress_levels,omitempty"`
	Volumes              []*Dictionary `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DictionariesResponse) Reset()         { *m = DictionariesResponse{} }
func (m *DictionariesResponse) String() string { return proto.CompactTextString(m) }
func (*DictionariesResponse) ProtoMessage()    {}
func (*DictionariesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48bb302865fe9053, []int{2}
}

func (m *DictionariesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionariesResponse.Unmarshal(m, b)
}
func (m *DictionariesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionariesResponse.Marshal(b, m, deterministic)
}
func (m *DictionariesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionariesResponse.Merge(m, src)
}
func (m *DictionariesResponse) XXX_Size() int {
	return xxx_messageInfo_DictionariesResponse.Size(m)
}
func (m *DictionariesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionariesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DictionariesResponse proto.InternalMessageInfo

func (m *DictionariesResponse) GetComplicationLevels() []*Dictionary {
	if m != nil {
		return m.ComplicationLevels
	}
	return nil
}

func (m *DictionariesResponse) GetFortressLevels() []*Dictionary {
	if m != nil {
		return m.FortressLevels
	}
	return nil
}

func (m *DictionariesResponse) GetVolumes() []*Dictionary {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func init() {
	proto.RegisterType((*DictionariesRequest)(nil), "proto.DictionariesRequest")
	proto.RegisterType((*Dictionary)(nil), "proto.Dictionary")
	proto.RegisterType((*DictionariesResponse)(nil), "proto.DictionariesResponse")
}

func init() { proto.RegisterFile("proto/dictionaries.proto", fileDescriptor_48bb302865fe9053) }

var fileDescriptor_48bb302865fe9053 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xc9, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x4b, 0x2c, 0xca, 0x4c, 0x2d, 0xd6, 0x03,
	0x0b, 0x09, 0xb1, 0x82, 0x29, 0x25, 0x51, 0x2e, 0x61, 0x17, 0x24, 0xc9, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x25, 0x03, 0x2e, 0x2e, 0xb8, 0x70, 0xa5, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62,
	0x6e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0x74, 0x98, 0x91, 0x4b, 0x04,
	0xd5, 0xa4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x27, 0x2e, 0xe1, 0xe4, 0xfc, 0xdc, 0x82,
	0x9c, 0xcc, 0xe4, 0x44, 0x90, 0x64, 0x7c, 0x4e, 0x6a, 0x59, 0x6a, 0x4e, 0xb1, 0x04, 0xa3, 0x02,
	0xb3, 0x06, 0xb7, 0x91, 0x20, 0xc4, 0x35, 0x7a, 0x08, 0xcb, 0x82, 0x84, 0x90, 0x55, 0xfb, 0x80,
	0x15, 0x0b, 0x59, 0x71, 0xf1, 0xa7, 0xe5, 0x17, 0x95, 0x14, 0xa5, 0x16, 0x17, 0xc3, 0xf4, 0x33,
	0xe1, 0xd2, 0xcf, 0x07, 0x53, 0x09, 0xd5, 0xab, 0xcd, 0xc5, 0x5e, 0x96, 0x9f, 0x53, 0x9a, 0x9b,
	0x5a, 0x2c, 0xc1, 0x8c, 0x4b, 0x0f, 0x4c, 0x85, 0x51, 0x0c, 0x17, 0x0f, 0xb2, 0x27, 0x84, 0x7c,
	0xb8, 0xf8, 0xdd, 0x53, 0x4b, 0x50, 0x84, 0xa4, 0xd0, 0xb5, 0x23, 0x82, 0x4d, 0x4a, 0x1a, 0xab,
	0x1c, 0x24, 0x20, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xb2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xad, 0x77, 0xb1, 0xf5, 0x96, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DictionariesClient is the client API for Dictionaries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictionariesClient interface {
	GetDictionaries(ctx context.Context, in *DictionariesRequest, opts ...grpc.CallOption) (*DictionariesResponse, error)
}

type dictionariesClient struct {
	cc grpc.ClientConnInterface
}

func NewDictionariesClient(cc grpc.ClientConnInterface) DictionariesClient {
	return &dictionariesClient{cc}
}

func (c *dictionariesClient) GetDictionaries(ctx context.Context, in *DictionariesRequest, opts ...grpc.CallOption) (*DictionariesResponse, error) {
	out := new(DictionariesResponse)
	err := c.cc.Invoke(ctx, "/proto.Dictionaries/GetDictionaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionariesServer is the server API for Dictionaries service.
type DictionariesServer interface {
	GetDictionaries(context.Context, *DictionariesRequest) (*DictionariesResponse, error)
}

// UnimplementedDictionariesServer can be embedded to have forward compatible implementations.
type UnimplementedDictionariesServer struct {
}

func (*UnimplementedDictionariesServer) GetDictionaries(ctx context.Context, req *DictionariesRequest) (*DictionariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaries not implemented")
}

func RegisterDictionariesServer(s *grpc.Server, srv DictionariesServer) {
	s.RegisterService(&_Dictionaries_serviceDesc, srv)
}

func _Dictionaries_GetDictionaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionariesServer).GetDictionaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dictionaries/GetDictionaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionariesServer).GetDictionaries(ctx, req.(*DictionariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dictionaries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dictionaries",
	HandlerType: (*DictionariesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDictionaries",
			Handler:    _Dictionaries_GetDictionaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dictionaries.proto",
}
