// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/complication_levels.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0bb2d86854f3109, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type ComplicationLevel struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComplicationLevel) Reset()         { *m = ComplicationLevel{} }
func (m *ComplicationLevel) String() string { return proto.CompactTextString(m) }
func (*ComplicationLevel) ProtoMessage()    {}
func (*ComplicationLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0bb2d86854f3109, []int{1}
}

func (m *ComplicationLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplicationLevel.Unmarshal(m, b)
}
func (m *ComplicationLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplicationLevel.Marshal(b, m, deterministic)
}
func (m *ComplicationLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplicationLevel.Merge(m, src)
}
func (m *ComplicationLevel) XXX_Size() int {
	return xxx_messageInfo_ComplicationLevel.Size(m)
}
func (m *ComplicationLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplicationLevel.DiscardUnknown(m)
}

var xxx_messageInfo_ComplicationLevel proto.InternalMessageInfo

func (m *ComplicationLevel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ComplicationLevel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComplicationLevel) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type ComplicationLevelsList struct {
	List                 []*ComplicationLevel `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ComplicationLevelsList) Reset()         { *m = ComplicationLevelsList{} }
func (m *ComplicationLevelsList) String() string { return proto.CompactTextString(m) }
func (*ComplicationLevelsList) ProtoMessage()    {}
func (*ComplicationLevelsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0bb2d86854f3109, []int{2}
}

func (m *ComplicationLevelsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplicationLevelsList.Unmarshal(m, b)
}
func (m *ComplicationLevelsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplicationLevelsList.Marshal(b, m, deterministic)
}
func (m *ComplicationLevelsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplicationLevelsList.Merge(m, src)
}
func (m *ComplicationLevelsList) XXX_Size() int {
	return xxx_messageInfo_ComplicationLevelsList.Size(m)
}
func (m *ComplicationLevelsList) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplicationLevelsList.DiscardUnknown(m)
}

var xxx_messageInfo_ComplicationLevelsList proto.InternalMessageInfo

func (m *ComplicationLevelsList) GetList() []*ComplicationLevel {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "complicationlevels.Request")
	proto.RegisterType((*ComplicationLevel)(nil), "complicationlevels.ComplicationLevel")
	proto.RegisterType((*ComplicationLevelsList)(nil), "complicationlevels.ComplicationLevelsList")
}

func init() { proto.RegisterFile("proto/complication_levels.proto", fileDescriptor_d0bb2d86854f3109) }

var fileDescriptor_d0bb2d86854f3109 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0x2d, 0xc8, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0xcf,
	0x49, 0x2d, 0x4b, 0xcd, 0x29, 0xd6, 0x03, 0xcb, 0x08, 0x09, 0x21, 0x4b, 0x41, 0x64, 0x94, 0x38,
	0xb9, 0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xbc, 0xb9, 0x04, 0x9d, 0x91, 0x14,
	0xf8, 0x80, 0x14, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06,
	0x31, 0x65, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0x92, 0xcc, 0xdc, 0x54, 0x09, 0x66, 0x88, 0x18, 0x88, 0xad,
	0x14, 0xcc, 0x25, 0x86, 0x61, 0x58, 0xb1, 0x4f, 0x66, 0x71, 0x89, 0x90, 0x25, 0x17, 0x4b, 0x4e,
	0x66, 0x71, 0x89, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xaa, 0x1e, 0xa6, 0xa3, 0xf4, 0x30,
	0x74, 0x06, 0x81, 0xb5, 0x18, 0xa5, 0x71, 0x09, 0x61, 0x1a, 0x2a, 0x14, 0xc0, 0xc5, 0xec, 0x9e,
	0x5a, 0x22, 0x24, 0x8d, 0xcd, 0x24, 0xa8, 0xdf, 0xa4, 0xb4, 0x88, 0xb2, 0x06, 0xec, 0x40, 0x25,
	0x86, 0x24, 0x36, 0x70, 0x78, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0xe9, 0x23, 0x5d,
	0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ComplicationLevelsClient is the client API for ComplicationLevels service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ComplicationLevelsClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ComplicationLevelsList, error)
}

type complicationLevelsClient struct {
	cc grpc.ClientConnInterface
}

func NewComplicationLevelsClient(cc grpc.ClientConnInterface) ComplicationLevelsClient {
	return &complicationLevelsClient{cc}
}

func (c *complicationLevelsClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ComplicationLevelsList, error) {
	out := new(ComplicationLevelsList)
	err := c.cc.Invoke(ctx, "/complicationlevels.ComplicationLevels/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplicationLevelsServer is the server API for ComplicationLevels service.
type ComplicationLevelsServer interface {
	Get(context.Context, *Request) (*ComplicationLevelsList, error)
}

// UnimplementedComplicationLevelsServer can be embedded to have forward compatible implementations.
type UnimplementedComplicationLevelsServer struct {
}

func (*UnimplementedComplicationLevelsServer) Get(ctx context.Context, req *Request) (*ComplicationLevelsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterComplicationLevelsServer(s *grpc.Server, srv ComplicationLevelsServer) {
	s.RegisterService(&_ComplicationLevels_serviceDesc, srv)
}

func _ComplicationLevels_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplicationLevelsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/complicationlevels.ComplicationLevels/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplicationLevelsServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ComplicationLevels_serviceDesc = grpc.ServiceDesc{
	ServiceName: "complicationlevels.ComplicationLevels",
	HandlerType: (*ComplicationLevelsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ComplicationLevels_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/complication_levels.proto",
}
