// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dictionaries.proto

package protogen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NameItem_Type int32

const (
	NameItem_COCKTAIL   NameItem_Type = 0
	NameItem_INGREDIENT NameItem_Type = 1
	NameItem_INSTRUMENT NameItem_Type = 2
)

var NameItem_Type_name = map[int32]string{
	0: "COCKTAIL",
	1: "INGREDIENT",
	2: "INSTRUMENT",
}

var NameItem_Type_value = map[string]int32{
	"COCKTAIL":   0,
	"INGREDIENT": 1,
	"INSTRUMENT": 2,
}

func (x NameItem_Type) String() string {
	return proto.EnumName(NameItem_Type_name, int32(x))
}

func (NameItem_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{4, 0}
}

type DictionariesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionariesRequest) Reset()         { *m = DictionariesRequest{} }
func (m *DictionariesRequest) String() string { return proto.CompactTextString(m) }
func (*DictionariesRequest) ProtoMessage()    {}
func (*DictionariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{0}
}

func (m *DictionariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionariesRequest.Unmarshal(m, b)
}
func (m *DictionariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionariesRequest.Marshal(b, m, deterministic)
}
func (m *DictionariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionariesRequest.Merge(m, src)
}
func (m *DictionariesRequest) XXX_Size() int {
	return xxx_messageInfo_DictionariesRequest.Size(m)
}
func (m *DictionariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DictionariesRequest proto.InternalMessageInfo

type Dictionary struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dictionary) Reset()         { *m = Dictionary{} }
func (m *Dictionary) String() string { return proto.CompactTextString(m) }
func (*Dictionary) ProtoMessage()    {}
func (*Dictionary) Descriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{1}
}

func (m *Dictionary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dictionary.Unmarshal(m, b)
}
func (m *Dictionary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dictionary.Marshal(b, m, deterministic)
}
func (m *Dictionary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dictionary.Merge(m, src)
}
func (m *Dictionary) XXX_Size() int {
	return xxx_messageInfo_Dictionary.Size(m)
}
func (m *Dictionary) XXX_DiscardUnknown() {
	xxx_messageInfo_Dictionary.DiscardUnknown(m)
}

var xxx_messageInfo_Dictionary proto.InternalMessageInfo

func (m *Dictionary) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Dictionary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DictionariesResponse struct {
	ComplicationLevels   []*Dictionary `protobuf:"bytes,1,rep,name=complication_levels,json=complicationLevels,proto3" json:"complication_levels,omitempty"`
	FortressLevels       []*Dictionary `protobuf:"bytes,2,rep,name=fortress_levels,json=fortressLevels,proto3" json:"fortress_levels,omitempty"`
	Volumes              []*Dictionary `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Ingredients          []*Dictionary `protobuf:"bytes,4,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Other                []*Dictionary `protobuf:"bytes,5,rep,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DictionariesResponse) Reset()         { *m = DictionariesResponse{} }
func (m *DictionariesResponse) String() string { return proto.CompactTextString(m) }
func (*DictionariesResponse) ProtoMessage()    {}
func (*DictionariesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{2}
}

func (m *DictionariesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionariesResponse.Unmarshal(m, b)
}
func (m *DictionariesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionariesResponse.Marshal(b, m, deterministic)
}
func (m *DictionariesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionariesResponse.Merge(m, src)
}
func (m *DictionariesResponse) XXX_Size() int {
	return xxx_messageInfo_DictionariesResponse.Size(m)
}
func (m *DictionariesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionariesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DictionariesResponse proto.InternalMessageInfo

func (m *DictionariesResponse) GetComplicationLevels() []*Dictionary {
	if m != nil {
		return m.ComplicationLevels
	}
	return nil
}

func (m *DictionariesResponse) GetFortressLevels() []*Dictionary {
	if m != nil {
		return m.FortressLevels
	}
	return nil
}

func (m *DictionariesResponse) GetVolumes() []*Dictionary {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func (m *DictionariesResponse) GetIngredients() []*Dictionary {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

func (m *DictionariesResponse) GetOther() []*Dictionary {
	if m != nil {
		return m.Other
	}
	return nil
}

type NameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameRequest) Reset()         { *m = NameRequest{} }
func (m *NameRequest) String() string { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()    {}
func (*NameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{3}
}

func (m *NameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRequest.Unmarshal(m, b)
}
func (m *NameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRequest.Marshal(b, m, deterministic)
}
func (m *NameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRequest.Merge(m, src)
}
func (m *NameRequest) XXX_Size() int {
	return xxx_messageInfo_NameRequest.Size(m)
}
func (m *NameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameRequest proto.InternalMessageInfo

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type NameItem struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 NameItem_Type `protobuf:"varint,3,opt,name=type,proto3,enum=proto.NameItem_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NameItem) Reset()         { *m = NameItem{} }
func (m *NameItem) String() string { return proto.CompactTextString(m) }
func (*NameItem) ProtoMessage()    {}
func (*NameItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{4}
}

func (m *NameItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameItem.Unmarshal(m, b)
}
func (m *NameItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameItem.Marshal(b, m, deterministic)
}
func (m *NameItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameItem.Merge(m, src)
}
func (m *NameItem) XXX_Size() int {
	return xxx_messageInfo_NameItem.Size(m)
}
func (m *NameItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NameItem.DiscardUnknown(m)
}

var xxx_messageInfo_NameItem proto.InternalMessageInfo

func (m *NameItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NameItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NameItem) GetType() NameItem_Type {
	if m != nil {
		return m.Type
	}
	return NameItem_COCKTAIL
}

type NameResponse struct {
	Items                []*NameItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NameResponse) Reset()         { *m = NameResponse{} }
func (m *NameResponse) String() string { return proto.CompactTextString(m) }
func (*NameResponse) ProtoMessage()    {}
func (*NameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b378073ffd87eff4, []int{5}
}

func (m *NameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameResponse.Unmarshal(m, b)
}
func (m *NameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameResponse.Marshal(b, m, deterministic)
}
func (m *NameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameResponse.Merge(m, src)
}
func (m *NameResponse) XXX_Size() int {
	return xxx_messageInfo_NameResponse.Size(m)
}
func (m *NameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NameResponse proto.InternalMessageInfo

func (m *NameResponse) GetItems() []*NameItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.NameItem_Type", NameItem_Type_name, NameItem_Type_value)
	proto.RegisterType((*DictionariesRequest)(nil), "proto.DictionariesRequest")
	proto.RegisterType((*Dictionary)(nil), "proto.Dictionary")
	proto.RegisterType((*DictionariesResponse)(nil), "proto.DictionariesResponse")
	proto.RegisterType((*NameRequest)(nil), "proto.NameRequest")
	proto.RegisterType((*NameItem)(nil), "proto.NameItem")
	proto.RegisterType((*NameResponse)(nil), "proto.NameResponse")
}

func init() { proto.RegisterFile("dictionaries.proto", fileDescriptor_b378073ffd87eff4) }

var fileDescriptor_b378073ffd87eff4 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x9f, 0xd3, 0x86, 0x6d, 0xaf, 0x55, 0xba, 0xb9, 0x43, 0x8a, 0xc6, 0xa5, 0xb2, 0x84, 0x88,
	0x84, 0x14, 0xa1, 0x8e, 0x71, 0x80, 0x13, 0xdd, 0xa6, 0xaa, 0xa2, 0x94, 0xc9, 0x94, 0x0b, 0x17,
	0x94, 0xb5, 0x8f, 0x61, 0xa9, 0x89, 0x83, 0xed, 0x0e, 0xf5, 0x4b, 0x70, 0xe2, 0x0b, 0xf0, 0x4d,
	0x51, 0xec, 0x64, 0x4d, 0x27, 0x22, 0xed, 0x14, 0xbf, 0xdf, 0x1f, 0xbf, 0x97, 0xdf, 0x33, 0xd0,
	0xa5, 0x58, 0x18, 0x21, 0xb3, 0x44, 0x09, 0xd4, 0x71, 0xae, 0xa4, 0x91, 0xd4, 0xb7, 0x1f, 0xf6,
	0x14, 0xfa, 0x97, 0x35, 0x92, 0xe3, 0xcf, 0x35, 0x6a, 0xc3, 0x5e, 0x01, 0xdc, 0xc3, 0x1b, 0x1a,
	0x80, 0x27, 0x96, 0x21, 0x19, 0x90, 0xc8, 0xe7, 0x9e, 0x58, 0x52, 0x0a, 0xed, 0x2c, 0x49, 0x31,
	0xf4, 0x06, 0x24, 0x3a, 0xe4, 0xf6, 0xcc, 0xfe, 0x7a, 0x70, 0xb2, 0x7b, 0x93, 0xce, 0x65, 0xa6,
	0x91, 0x8e, 0xa0, 0xbf, 0x90, 0x69, 0xbe, 0x12, 0x8b, 0xa4, 0x20, 0xbf, 0xad, 0xf0, 0x0e, 0x57,
	0x3a, 0x24, 0x83, 0x56, 0xd4, 0x19, 0x1e, 0xbb, 0x69, 0xe2, 0x6d, 0x33, 0x4e, 0xeb, 0xea, 0xa9,
	0x15, 0xd3, 0xb7, 0xd0, 0xfb, 0x2e, 0x95, 0x51, 0xa8, 0x75, 0xe5, 0xf7, 0x9a, 0xfc, 0x41, 0xa5,
	0x2c, 0xbd, 0x2f, 0x61, 0xff, 0x4e, 0xae, 0xd6, 0x29, 0xea, 0xb0, 0xd5, 0xe4, 0xa9, 0x14, 0xf4,
	0x0c, 0x3a, 0x22, 0xbb, 0x55, 0xb8, 0x14, 0x98, 0x19, 0x1d, 0xb6, 0x9b, 0x0c, 0x75, 0x15, 0x7d,
	0x01, 0xbe, 0x34, 0x3f, 0x50, 0x85, 0x7e, 0x93, 0xdc, 0xf1, 0xec, 0x1c, 0x3a, 0xb3, 0x24, 0xc5,
	0x32, 0xe4, 0xfb, 0x18, 0xc9, 0x36, 0xc6, 0x02, 0xcb, 0x93, 0x5b, 0x17, 0xad, 0xcf, 0xed, 0x99,
	0xfd, 0x26, 0x70, 0x50, 0xf8, 0x26, 0x06, 0xd3, 0xc7, 0xec, 0x82, 0x46, 0xd0, 0x36, 0x9b, 0x1c,
	0xc3, 0xd6, 0x80, 0x44, 0xc1, 0xf0, 0xa4, 0x9c, 0xa7, 0xba, 0x22, 0x9e, 0x6f, 0x72, 0xe4, 0x56,
	0xc1, 0x5e, 0x43, 0xbb, 0xa8, 0x68, 0x17, 0x0e, 0x2e, 0x3e, 0x5d, 0x7c, 0x98, 0xbf, 0x9f, 0x4c,
	0x8f, 0xf6, 0x68, 0x00, 0x30, 0x99, 0x8d, 0xf9, 0xd5, 0xe5, 0xe4, 0x6a, 0x36, 0x3f, 0x22, 0xae,
	0xfe, 0x3c, 0xe7, 0x5f, 0x3e, 0x16, 0xb5, 0xc7, 0xce, 0xa1, 0xeb, 0xfe, 0xa3, 0x5c, 0xf1, 0x73,
	0xf0, 0x85, 0xc1, 0xb4, 0x5a, 0x6a, 0xef, 0x41, 0x43, 0xee, 0xd8, 0xe1, 0x1f, 0x02, 0xdd, 0xfa,
	0x13, 0xa1, 0x53, 0xe8, 0x8d, 0xd1, 0xec, 0x40, 0xa7, 0x0f, 0xc3, 0xdb, 0x3e, 0xca, 0xd3, 0x67,
	0xff, 0xe5, 0xdc, 0x0c, 0x6c, 0x8f, 0xbe, 0x81, 0xc3, 0x31, 0x9a, 0xd1, 0x66, 0x66, 0x73, 0xac,
	0xcd, 0x50, 0xf9, 0xfb, 0x3b, 0x58, 0xe5, 0x1b, 0xc5, 0x10, 0xa8, 0x75, 0xfc, 0x0b, 0x6f, 0x50,
	0x39, 0xc1, 0xe8, 0xb8, 0xde, 0xe1, 0xba, 0x80, 0xae, 0xc9, 0xd7, 0xfd, 0xf8, 0x9d, 0x65, 0x6f,
	0x9e, 0xd8, 0xcf, 0xd9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xcf, 0x4f, 0x20, 0x56, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DictionariesClient is the client API for Dictionaries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DictionariesClient interface {
	GetDictionaries(ctx context.Context, in *DictionariesRequest, opts ...grpc.CallOption) (*DictionariesResponse, error)
	GetByName(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
}

type dictionariesClient struct {
	cc grpc.ClientConnInterface
}

func NewDictionariesClient(cc grpc.ClientConnInterface) DictionariesClient {
	return &dictionariesClient{cc}
}

func (c *dictionariesClient) GetDictionaries(ctx context.Context, in *DictionariesRequest, opts ...grpc.CallOption) (*DictionariesResponse, error) {
	out := new(DictionariesResponse)
	err := c.cc.Invoke(ctx, "/proto.Dictionaries/GetDictionaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionariesClient) GetByName(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, "/proto.Dictionaries/GetByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionariesServer is the server API for Dictionaries service.
type DictionariesServer interface {
	GetDictionaries(context.Context, *DictionariesRequest) (*DictionariesResponse, error)
	GetByName(context.Context, *NameRequest) (*NameResponse, error)
}

// UnimplementedDictionariesServer can be embedded to have forward compatible implementations.
type UnimplementedDictionariesServer struct {
}

func (*UnimplementedDictionariesServer) GetDictionaries(ctx context.Context, req *DictionariesRequest) (*DictionariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaries not implemented")
}
func (*UnimplementedDictionariesServer) GetByName(ctx context.Context, req *NameRequest) (*NameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByName not implemented")
}

func RegisterDictionariesServer(s *grpc.Server, srv DictionariesServer) {
	s.RegisterService(&_Dictionaries_serviceDesc, srv)
}

func _Dictionaries_GetDictionaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionariesServer).GetDictionaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dictionaries/GetDictionaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionariesServer).GetDictionaries(ctx, req.(*DictionariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionaries_GetByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionariesServer).GetByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dictionaries/GetByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionariesServer).GetByName(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dictionaries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dictionaries",
	HandlerType: (*DictionariesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDictionaries",
			Handler:    _Dictionaries_GetDictionaries_Handler,
		},
		{
			MethodName: "GetByName",
			Handler:    _Dictionaries_GetByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dictionaries.proto",
}
