// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drinks.proto

package protogen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DrinkRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrinkRequest) Reset()         { *m = DrinkRequest{} }
func (m *DrinkRequest) String() string { return proto.CompactTextString(m) }
func (*DrinkRequest) ProtoMessage()    {}
func (*DrinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{0}
}

func (m *DrinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkRequest.Unmarshal(m, b)
}
func (m *DrinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkRequest.Marshal(b, m, deterministic)
}
func (m *DrinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkRequest.Merge(m, src)
}
func (m *DrinkRequest) XXX_Size() int {
	return xxx_messageInfo_DrinkRequest.Size(m)
}
func (m *DrinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkRequest proto.InternalMessageInfo

func (m *DrinkRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DrinkTryRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrinkTryRequest) Reset()         { *m = DrinkTryRequest{} }
func (m *DrinkTryRequest) String() string { return proto.CompactTextString(m) }
func (*DrinkTryRequest) ProtoMessage()    {}
func (*DrinkTryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{1}
}

func (m *DrinkTryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkTryRequest.Unmarshal(m, b)
}
func (m *DrinkTryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkTryRequest.Marshal(b, m, deterministic)
}
func (m *DrinkTryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkTryRequest.Merge(m, src)
}
func (m *DrinkTryRequest) XXX_Size() int {
	return xxx_messageInfo_DrinkTryRequest.Size(m)
}
func (m *DrinkTryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkTryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkTryRequest proto.InternalMessageInfo

func (m *DrinkTryRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DrinkTryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DrinkMarkRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mark                 int32    `protobuf:"varint,2,opt,name=mark,proto3" json:"mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrinkMarkRequest) Reset()         { *m = DrinkMarkRequest{} }
func (m *DrinkMarkRequest) String() string { return proto.CompactTextString(m) }
func (*DrinkMarkRequest) ProtoMessage()    {}
func (*DrinkMarkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{2}
}

func (m *DrinkMarkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkMarkRequest.Unmarshal(m, b)
}
func (m *DrinkMarkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkMarkRequest.Marshal(b, m, deterministic)
}
func (m *DrinkMarkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkMarkRequest.Merge(m, src)
}
func (m *DrinkMarkRequest) XXX_Size() int {
	return xxx_messageInfo_DrinkMarkRequest.Size(m)
}
func (m *DrinkMarkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkMarkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkMarkRequest proto.InternalMessageInfo

func (m *DrinkMarkRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DrinkMarkRequest) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DrinkMarkResponse struct {
	Mark                 int32    `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	MarkDescription      string   `protobuf:"bytes,2,opt,name=mark_description,json=markDescription,proto3" json:"mark_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrinkMarkResponse) Reset()         { *m = DrinkMarkResponse{} }
func (m *DrinkMarkResponse) String() string { return proto.CompactTextString(m) }
func (*DrinkMarkResponse) ProtoMessage()    {}
func (*DrinkMarkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{4}
}

func (m *DrinkMarkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkMarkResponse.Unmarshal(m, b)
}
func (m *DrinkMarkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkMarkResponse.Marshal(b, m, deterministic)
}
func (m *DrinkMarkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkMarkResponse.Merge(m, src)
}
func (m *DrinkMarkResponse) XXX_Size() int {
	return xxx_messageInfo_DrinkMarkResponse.Size(m)
}
func (m *DrinkMarkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkMarkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkMarkResponse proto.InternalMessageInfo

func (m *DrinkMarkResponse) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

func (m *DrinkMarkResponse) GetMarkDescription() string {
	if m != nil {
		return m.MarkDescription
	}
	return ""
}

type DrinksRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Fortress             []int32  `protobuf:"varint,2,rep,packed,name=fortress,proto3" json:"fortress,omitempty"`
	Complication         []int32  `protobuf:"varint,3,rep,packed,name=complication,proto3" json:"complication,omitempty"`
	Volume               []int32  `protobuf:"varint,4,rep,packed,name=volume,proto3" json:"volume,omitempty"`
	IsFlacky             bool     `protobuf:"varint,5,opt,name=is_flacky,json=isFlacky,proto3" json:"is_flacky,omitempty"`
	IsFire               bool     `protobuf:"varint,6,opt,name=is_fire,json=isFire,proto3" json:"is_fire,omitempty"`
	IsIba                bool     `protobuf:"varint,7,opt,name=is_iba,json=isIba,proto3" json:"is_iba,omitempty"`
	Includes             []int32  `protobuf:"varint,8,rep,packed,name=includes,proto3" json:"includes,omitempty"`
	Except               []int32  `protobuf:"varint,9,rep,packed,name=except,proto3" json:"except,omitempty"`
	Instruments          []int32  `protobuf:"varint,10,rep,packed,name=instruments,proto3" json:"instruments,omitempty"`
	Similar              []int32  `protobuf:"varint,11,rep,packed,name=similar,proto3" json:"similar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrinksRequest) Reset()         { *m = DrinksRequest{} }
func (m *DrinksRequest) String() string { return proto.CompactTextString(m) }
func (*DrinksRequest) ProtoMessage()    {}
func (*DrinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{5}
}

func (m *DrinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinksRequest.Unmarshal(m, b)
}
func (m *DrinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinksRequest.Marshal(b, m, deterministic)
}
func (m *DrinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinksRequest.Merge(m, src)
}
func (m *DrinksRequest) XXX_Size() int {
	return xxx_messageInfo_DrinksRequest.Size(m)
}
func (m *DrinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrinksRequest proto.InternalMessageInfo

func (m *DrinksRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DrinksRequest) GetFortress() []int32 {
	if m != nil {
		return m.Fortress
	}
	return nil
}

func (m *DrinksRequest) GetComplication() []int32 {
	if m != nil {
		return m.Complication
	}
	return nil
}

func (m *DrinksRequest) GetVolume() []int32 {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *DrinksRequest) GetIsFlacky() bool {
	if m != nil {
		return m.IsFlacky
	}
	return false
}

func (m *DrinksRequest) GetIsFire() bool {
	if m != nil {
		return m.IsFire
	}
	return false
}

func (m *DrinksRequest) GetIsIba() bool {
	if m != nil {
		return m.IsIba
	}
	return false
}

func (m *DrinksRequest) GetIncludes() []int32 {
	if m != nil {
		return m.Includes
	}
	return nil
}

func (m *DrinksRequest) GetExcept() []int32 {
	if m != nil {
		return m.Except
	}
	return nil
}

func (m *DrinksRequest) GetInstruments() []int32 {
	if m != nil {
		return m.Instruments
	}
	return nil
}

func (m *DrinksRequest) GetSimilar() []int32 {
	if m != nil {
		return m.Similar
	}
	return nil
}

type DrinkItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsFlacky             bool     `protobuf:"varint,2,opt,name=is_flacky,json=isFlacky,proto3" json:"is_flacky,omitempty"`
	IsFire               bool     `protobuf:"varint,3,opt,name=is_fire,json=isFire,proto3" json:"is_fire,omitempty"`
	IsIba                bool     `protobuf:"varint,4,opt,name=is_iba,json=isIba,proto3" json:"is_iba,omitempty"`
	Mark                 int32    `protobuf:"varint,5,opt,name=mark,proto3" json:"mark,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Properties           string   `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	Ingredients          string   `protobuf:"bytes,8,opt,name=ingredients,proto3" json:"ingredients,omitempty"`
	Icon                 string   `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrinkItem) Reset()         { *m = DrinkItem{} }
func (m *DrinkItem) String() string { return proto.CompactTextString(m) }
func (*DrinkItem) ProtoMessage()    {}
func (*DrinkItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{6}
}

func (m *DrinkItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkItem.Unmarshal(m, b)
}
func (m *DrinkItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkItem.Marshal(b, m, deterministic)
}
func (m *DrinkItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkItem.Merge(m, src)
}
func (m *DrinkItem) XXX_Size() int {
	return xxx_messageInfo_DrinkItem.Size(m)
}
func (m *DrinkItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkItem.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkItem proto.InternalMessageInfo

func (m *DrinkItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DrinkItem) GetIsFlacky() bool {
	if m != nil {
		return m.IsFlacky
	}
	return false
}

func (m *DrinkItem) GetIsFire() bool {
	if m != nil {
		return m.IsFire
	}
	return false
}

func (m *DrinkItem) GetIsIba() bool {
	if m != nil {
		return m.IsIba
	}
	return false
}

func (m *DrinkItem) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

func (m *DrinkItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DrinkItem) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

func (m *DrinkItem) GetIngredients() string {
	if m != nil {
		return m.Ingredients
	}
	return ""
}

func (m *DrinkItem) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type Instrument struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instrument) Reset()         { *m = Instrument{} }
func (m *Instrument) String() string { return proto.CompactTextString(m) }
func (*Instrument) ProtoMessage()    {}
func (*Instrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{7}
}

func (m *Instrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instrument.Unmarshal(m, b)
}
func (m *Instrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instrument.Marshal(b, m, deterministic)
}
func (m *Instrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instrument.Merge(m, src)
}
func (m *Instrument) XXX_Size() int {
	return xxx_messageInfo_Instrument.Size(m)
}
func (m *Instrument) XXX_DiscardUnknown() {
	xxx_messageInfo_Instrument.DiscardUnknown(m)
}

var xxx_messageInfo_Instrument proto.InternalMessageInfo

func (m *Instrument) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Instrument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instrument) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Ingredient struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Volume               string   `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{8}
}

func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (m *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(m, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredient) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

type DrinkOfDayResponse struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsFlacky             bool          `protobuf:"varint,2,opt,name=is_flacky,json=isFlacky,proto3" json:"is_flacky,omitempty"`
	IsFire               bool          `protobuf:"varint,3,opt,name=is_fire,json=isFire,proto3" json:"is_fire,omitempty"`
	IsIba                bool          `protobuf:"varint,4,opt,name=is_iba,json=isIba,proto3" json:"is_iba,omitempty"`
	Mark                 int32         `protobuf:"varint,5,opt,name=mark,proto3" json:"mark,omitempty"`
	Name                 string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Complication         string        `protobuf:"bytes,8,opt,name=complication,proto3" json:"complication,omitempty"`
	Fortress             string        `protobuf:"bytes,9,opt,name=fortress,proto3" json:"fortress,omitempty"`
	Recipe               string        `protobuf:"bytes,10,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Description          string        `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	TriedBy              string        `protobuf:"bytes,12,opt,name=tried_by,json=triedBy,proto3" json:"tried_by,omitempty"`
	Preview              string        `protobuf:"bytes,13,opt,name=preview,proto3" json:"preview,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,14,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Instruments          []*Instrument `protobuf:"bytes,15,rep,name=instruments,proto3" json:"instruments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DrinkOfDayResponse) Reset()         { *m = DrinkOfDayResponse{} }
func (m *DrinkOfDayResponse) String() string { return proto.CompactTextString(m) }
func (*DrinkOfDayResponse) ProtoMessage()    {}
func (*DrinkOfDayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{9}
}

func (m *DrinkOfDayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkOfDayResponse.Unmarshal(m, b)
}
func (m *DrinkOfDayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkOfDayResponse.Marshal(b, m, deterministic)
}
func (m *DrinkOfDayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkOfDayResponse.Merge(m, src)
}
func (m *DrinkOfDayResponse) XXX_Size() int {
	return xxx_messageInfo_DrinkOfDayResponse.Size(m)
}
func (m *DrinkOfDayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkOfDayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkOfDayResponse proto.InternalMessageInfo

func (m *DrinkOfDayResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DrinkOfDayResponse) GetIsFlacky() bool {
	if m != nil {
		return m.IsFlacky
	}
	return false
}

func (m *DrinkOfDayResponse) GetIsFire() bool {
	if m != nil {
		return m.IsFire
	}
	return false
}

func (m *DrinkOfDayResponse) GetIsIba() bool {
	if m != nil {
		return m.IsIba
	}
	return false
}

func (m *DrinkOfDayResponse) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

func (m *DrinkOfDayResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DrinkOfDayResponse) GetComplication() string {
	if m != nil {
		return m.Complication
	}
	return ""
}

func (m *DrinkOfDayResponse) GetFortress() string {
	if m != nil {
		return m.Fortress
	}
	return ""
}

func (m *DrinkOfDayResponse) GetRecipe() string {
	if m != nil {
		return m.Recipe
	}
	return ""
}

func (m *DrinkOfDayResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DrinkOfDayResponse) GetTriedBy() string {
	if m != nil {
		return m.TriedBy
	}
	return ""
}

func (m *DrinkOfDayResponse) GetPreview() string {
	if m != nil {
		return m.Preview
	}
	return ""
}

func (m *DrinkOfDayResponse) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

func (m *DrinkOfDayResponse) GetInstruments() []*Instrument {
	if m != nil {
		return m.Instruments
	}
	return nil
}

type DrinksResponse struct {
	Drinks               []*DrinkItem `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DrinksResponse) Reset()         { *m = DrinksResponse{} }
func (m *DrinksResponse) String() string { return proto.CompactTextString(m) }
func (*DrinksResponse) ProtoMessage()    {}
func (*DrinksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{10}
}

func (m *DrinksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinksResponse.Unmarshal(m, b)
}
func (m *DrinksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinksResponse.Marshal(b, m, deterministic)
}
func (m *DrinksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinksResponse.Merge(m, src)
}
func (m *DrinksResponse) XXX_Size() int {
	return xxx_messageInfo_DrinksResponse.Size(m)
}
func (m *DrinksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrinksResponse proto.InternalMessageInfo

func (m *DrinksResponse) GetDrinks() []*DrinkItem {
	if m != nil {
		return m.Drinks
	}
	return nil
}

type DrinkResponse struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsFlacky             bool          `protobuf:"varint,2,opt,name=is_flacky,json=isFlacky,proto3" json:"is_flacky,omitempty"`
	IsFire               bool          `protobuf:"varint,3,opt,name=is_fire,json=isFire,proto3" json:"is_fire,omitempty"`
	IsIba                bool          `protobuf:"varint,4,opt,name=is_iba,json=isIba,proto3" json:"is_iba,omitempty"`
	Mark                 int32         `protobuf:"varint,5,opt,name=mark,proto3" json:"mark,omitempty"`
	Name                 string        `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	NameEn               string        `protobuf:"bytes,7,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Complication         string        `protobuf:"bytes,8,opt,name=complication,proto3" json:"complication,omitempty"`
	Fortress             string        `protobuf:"bytes,9,opt,name=fortress,proto3" json:"fortress,omitempty"`
	Recipe               string        `protobuf:"bytes,10,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Description          string        `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	TriedBy              string        `protobuf:"bytes,12,opt,name=tried_by,json=triedBy,proto3" json:"tried_by,omitempty"`
	MarkDescription      string        `protobuf:"bytes,13,opt,name=mark_description,json=markDescription,proto3" json:"mark_description,omitempty"`
	Icon                 string        `protobuf:"bytes,14,opt,name=icon,proto3" json:"icon,omitempty"`
	Instruments          []*Instrument `protobuf:"bytes,15,rep,name=instruments,proto3" json:"instruments,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,16,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DrinkResponse) Reset()         { *m = DrinkResponse{} }
func (m *DrinkResponse) String() string { return proto.CompactTextString(m) }
func (*DrinkResponse) ProtoMessage()    {}
func (*DrinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b541685a91b5bd2, []int{11}
}

func (m *DrinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrinkResponse.Unmarshal(m, b)
}
func (m *DrinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrinkResponse.Marshal(b, m, deterministic)
}
func (m *DrinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrinkResponse.Merge(m, src)
}
func (m *DrinkResponse) XXX_Size() int {
	return xxx_messageInfo_DrinkResponse.Size(m)
}
func (m *DrinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrinkResponse proto.InternalMessageInfo

func (m *DrinkResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DrinkResponse) GetIsFlacky() bool {
	if m != nil {
		return m.IsFlacky
	}
	return false
}

func (m *DrinkResponse) GetIsFire() bool {
	if m != nil {
		return m.IsFire
	}
	return false
}

func (m *DrinkResponse) GetIsIba() bool {
	if m != nil {
		return m.IsIba
	}
	return false
}

func (m *DrinkResponse) GetMark() int32 {
	if m != nil {
		return m.Mark
	}
	return 0
}

func (m *DrinkResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DrinkResponse) GetNameEn() string {
	if m != nil {
		return m.NameEn
	}
	return ""
}

func (m *DrinkResponse) GetComplication() string {
	if m != nil {
		return m.Complication
	}
	return ""
}

func (m *DrinkResponse) GetFortress() string {
	if m != nil {
		return m.Fortress
	}
	return ""
}

func (m *DrinkResponse) GetRecipe() string {
	if m != nil {
		return m.Recipe
	}
	return ""
}

func (m *DrinkResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DrinkResponse) GetTriedBy() string {
	if m != nil {
		return m.TriedBy
	}
	return ""
}

func (m *DrinkResponse) GetMarkDescription() string {
	if m != nil {
		return m.MarkDescription
	}
	return ""
}

func (m *DrinkResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *DrinkResponse) GetInstruments() []*Instrument {
	if m != nil {
		return m.Instruments
	}
	return nil
}

func (m *DrinkResponse) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

func init() {
	proto.RegisterType((*DrinkRequest)(nil), "proto.DrinkRequest")
	proto.RegisterType((*DrinkTryRequest)(nil), "proto.DrinkTryRequest")
	proto.RegisterType((*DrinkMarkRequest)(nil), "proto.DrinkMarkRequest")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*DrinkMarkResponse)(nil), "proto.DrinkMarkResponse")
	proto.RegisterType((*DrinksRequest)(nil), "proto.DrinksRequest")
	proto.RegisterType((*DrinkItem)(nil), "proto.DrinkItem")
	proto.RegisterType((*Instrument)(nil), "proto.Instrument")
	proto.RegisterType((*Ingredient)(nil), "proto.Ingredient")
	proto.RegisterType((*DrinkOfDayResponse)(nil), "proto.DrinkOfDayResponse")
	proto.RegisterType((*DrinksResponse)(nil), "proto.DrinksResponse")
	proto.RegisterType((*DrinkResponse)(nil), "proto.DrinkResponse")
}

func init() { proto.RegisterFile("drinks.proto", fileDescriptor_9b541685a91b5bd2) }

var fileDescriptor_9b541685a91b5bd2 = []byte{
	// 791 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x3b, 0x6f, 0xe3, 0x38,
	0x10, 0x8e, 0x64, 0x4b, 0xb6, 0xc6, 0x8f, 0x38, 0xbc, 0x3c, 0x18, 0x1f, 0x10, 0x18, 0xac, 0x7c,
	0x8d, 0x8b, 0x04, 0xb8, 0x03, 0x9c, 0xce, 0x97, 0xe4, 0xce, 0xc5, 0xe1, 0x02, 0x6d, 0xaa, 0x6d,
	0x0c, 0x59, 0x62, 0x02, 0x22, 0xd6, 0x63, 0x49, 0x39, 0x59, 0xff, 0xad, 0xad, 0x16, 0xd8, 0xff,
	0xb3, 0xcd, 0xfe, 0x89, 0x05, 0x49, 0xc9, 0xa6, 0x9c, 0x18, 0x08, 0xb6, 0x4a, 0x25, 0x7e, 0xdf,
	0x70, 0x86, 0xc3, 0x79, 0x51, 0xd0, 0x8e, 0x38, 0x4b, 0x1e, 0xc5, 0x28, 0xe3, 0x69, 0x9e, 0x22,
	0x47, 0x7d, 0xc8, 0x19, 0xb4, 0xaf, 0x24, 0xed, 0xd3, 0x4f, 0x4b, 0x2a, 0x72, 0xd4, 0x05, 0x9b,
	0x45, 0xd8, 0x1a, 0x58, 0x43, 0xc7, 0xb7, 0x59, 0x44, 0xc6, 0xb0, 0xaf, 0xe4, 0x77, 0x7c, 0xb5,
	0x63, 0x0b, 0x3a, 0x81, 0xc6, 0x52, 0x50, 0x3e, 0x63, 0x11, 0xb6, 0x07, 0xd6, 0xd0, 0xf3, 0x5d,
	0x09, 0xa7, 0x11, 0xf9, 0x13, 0x7a, 0x4a, 0xf7, 0xbf, 0x80, 0xef, 0xb2, 0x8f, 0x10, 0xd4, 0xe3,
	0x80, 0x3f, 0x2a, 0x4d, 0xc7, 0x57, 0x6b, 0xd2, 0x00, 0xe7, 0x3a, 0xce, 0xf2, 0x15, 0xf1, 0xe1,
	0xc0, 0x30, 0x20, 0xb2, 0x34, 0x11, 0x74, 0xad, 0x61, 0x6d, 0x34, 0xd0, 0x1f, 0xd0, 0x93, 0xdf,
	0x59, 0x44, 0x45, 0xc8, 0x59, 0x96, 0xb3, 0x34, 0x29, 0x7c, 0xd9, 0x97, 0xfc, 0xd5, 0x86, 0x26,
	0x5f, 0x6d, 0xe8, 0x28, 0xa3, 0xa2, 0x74, 0x09, 0x41, 0x3d, 0x0b, 0x1e, 0x68, 0x69, 0x50, 0xae,
	0x51, 0x1f, 0x9a, 0xf7, 0x29, 0xcf, 0x39, 0x15, 0x02, 0xdb, 0x83, 0xda, 0xd0, 0xf1, 0xd7, 0x18,
	0x11, 0x68, 0x87, 0x69, 0x9c, 0x2d, 0x58, 0x18, 0xa8, 0x83, 0x6a, 0x4a, 0x5e, 0xe1, 0xd0, 0x31,
	0xb8, 0x4f, 0xe9, 0x62, 0x19, 0x53, 0x5c, 0x57, 0xd2, 0x02, 0xa1, 0xdf, 0xc1, 0x63, 0x62, 0x76,
	0xbf, 0x08, 0xc2, 0xc7, 0x15, 0x76, 0x06, 0xd6, 0xb0, 0xe9, 0x37, 0x99, 0xb8, 0x51, 0x58, 0x06,
	0x52, 0x0a, 0x19, 0xa7, 0xd8, 0x55, 0x22, 0x97, 0x89, 0x1b, 0xc6, 0x29, 0x3a, 0x02, 0x97, 0x89,
	0x19, 0x9b, 0x07, 0xb8, 0xa1, 0x78, 0x87, 0x89, 0xe9, 0x3c, 0x90, 0x4e, 0xb2, 0x24, 0x5c, 0x2c,
	0x23, 0x2a, 0x70, 0x53, 0x3b, 0x59, 0x62, 0xe9, 0x00, 0xfd, 0x1c, 0xd2, 0x2c, 0xc7, 0x9e, 0x76,
	0x40, 0x23, 0x34, 0x80, 0x16, 0x4b, 0x44, 0xce, 0x97, 0x31, 0x4d, 0x72, 0x81, 0x41, 0x09, 0x4d,
	0x0a, 0x61, 0x68, 0x08, 0x16, 0xb3, 0x45, 0xc0, 0x71, 0x4b, 0x49, 0x4b, 0x48, 0xbe, 0x5b, 0xe0,
	0xa9, 0xd0, 0x4d, 0x73, 0x1a, 0xbf, 0xc8, 0x64, 0xe5, 0x6a, 0xf6, 0xee, 0xab, 0xd5, 0x76, 0x5c,
	0xad, 0x6e, 0x5e, 0xad, 0x4c, 0xb2, 0x63, 0x24, 0x19, 0x41, 0x3d, 0x09, 0x62, 0x1d, 0x1b, 0xcf,
	0x57, 0x6b, 0x74, 0x06, 0x90, 0xf1, 0x34, 0xa3, 0x3c, 0x67, 0x54, 0xa8, 0xe8, 0x78, 0xbe, 0xc1,
	0xe8, 0xeb, 0x3e, 0x70, 0x1a, 0x31, 0x75, 0xdd, 0xa6, 0xda, 0x60, 0x52, 0xd2, 0x2a, 0x0b, 0xd3,
	0x04, 0x7b, 0xda, 0xaa, 0x5c, 0x93, 0x1b, 0x80, 0xe9, 0x3a, 0x22, 0xaf, 0x95, 0xac, 0xf2, 0xc3,
	0x36, 0xfc, 0x38, 0x04, 0x87, 0xc5, 0xb2, 0x88, 0x6a, 0x8a, 0xd4, 0x80, 0xfc, 0x2b, 0xed, 0x94,
	0x47, 0xbd, 0xc9, 0xce, 0xa6, 0x6e, 0xb4, 0xa1, 0x02, 0x91, 0x2f, 0x35, 0x40, 0x2a, 0xf4, 0xff,
	0xdf, 0x5f, 0x05, 0xab, 0x75, 0x2f, 0xbc, 0x8b, 0x1c, 0x6c, 0xf7, 0x83, 0x0e, 0x72, 0xb5, 0x1f,
	0xcc, 0x7e, 0xd2, 0x91, 0xde, 0xf4, 0xd3, 0x31, 0xb8, 0x9c, 0x86, 0x2c, 0xa3, 0x18, 0xf4, 0x9d,
	0x35, 0x92, 0xb9, 0x33, 0xfb, 0xb9, 0xa5, 0x73, 0x67, 0x50, 0xe8, 0x14, 0x9a, 0x39, 0x67, 0x34,
	0x9a, 0xcd, 0x57, 0xb8, 0xad, 0xc4, 0x0d, 0x85, 0x27, 0x2b, 0x59, 0xc5, 0x19, 0xa7, 0x4f, 0x8c,
	0x3e, 0xe3, 0x8e, 0x96, 0x14, 0x10, 0x5d, 0x54, 0x4b, 0xa2, 0x3b, 0xa8, 0x0d, 0x5b, 0xe7, 0x07,
	0x7a, 0x2a, 0x8e, 0x36, 0xe9, 0xaa, 0x56, 0xc9, 0x45, 0xb5, 0x6d, 0xf6, 0xb7, 0x94, 0x4a, 0x49,
	0xa5, 0x93, 0xc8, 0x18, 0xba, 0xe5, 0xa4, 0x29, 0xf2, 0x35, 0x04, 0x57, 0x0f, 0x61, 0x6c, 0x29,
	0x0b, 0xbd, 0xc2, 0xc2, 0xba, 0xab, 0xfc, 0x42, 0x4e, 0x7e, 0xd4, 0x8a, 0x31, 0xf5, 0xbe, 0x72,
	0x7d, 0x02, 0x0d, 0xf9, 0x9d, 0xd1, 0xa4, 0x68, 0x36, 0x57, 0xc2, 0xeb, 0xe4, 0x7d, 0x16, 0xc1,
	0x6b, 0xcf, 0x42, 0xe7, 0xd5, 0x67, 0x61, 0x3d, 0x06, 0xba, 0x9b, 0x31, 0xf0, 0x4b, 0x49, 0xdf,
	0x2e, 0xaf, 0xde, 0x5b, 0xca, 0xeb, 0xfc, 0x9b, 0x0d, 0xae, 0x2e, 0x15, 0x34, 0x06, 0xef, 0x1f,
	0x9a, 0x17, 0xe0, 0xd0, 0xac, 0x8f, 0xf2, 0xc1, 0xea, 0x1f, 0x6d, 0xb1, 0xba, 0x40, 0xc8, 0x1e,
	0x1a, 0x43, 0xa7, 0xd4, 0x55, 0x73, 0x02, 0xb5, 0x8b, 0x9d, 0xea, 0x39, 0xed, 0x9f, 0x9a, 0x7a,
	0x95, 0x41, 0x42, 0xf6, 0xd0, 0x25, 0xb4, 0x4b, 0xdd, 0xc9, 0x6a, 0x1a, 0xa1, 0xdf, 0xcc, 0xcd,
	0xe5, 0xc9, 0x87, 0x55, 0x72, 0xad, 0xfc, 0x17, 0x74, 0x3e, 0x14, 0xca, 0x77, 0x32, 0xf6, 0xe8,
	0xd8, 0xdc, 0xb8, 0xf9, 0x77, 0xe8, 0x57, 0x1c, 0x22, 0x7b, 0xe8, 0x6f, 0x68, 0x97, 0x8a, 0xf2,
	0x91, 0x47, 0x27, 0xa6, 0x9e, 0xf1, 0xdf, 0xd0, 0xc7, 0x2f, 0x05, 0xe5, 0xe9, 0x93, 0x21, 0x74,
	0xf9, 0x72, 0xf4, 0x4c, 0xe7, 0x94, 0xeb, 0x5d, 0x93, 0x96, 0x0e, 0xcd, 0xad, 0x04, 0xb7, 0xd6,
	0xc7, 0xc6, 0xe8, 0x52, 0xf1, 0x73, 0x57, 0x7d, 0x2e, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x6c,
	0x80, 0x88, 0xc8, 0x0b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DrinksClient is the client API for Drinks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrinksClient interface {
	GetDrinks(ctx context.Context, in *DrinksRequest, opts ...grpc.CallOption) (*DrinksResponse, error)
	GetDrinkOfDay(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DrinkOfDayResponse, error)
	GetDrinkById(ctx context.Context, in *DrinkRequest, opts ...grpc.CallOption) (*DrinkResponse, error)
	SetDrinkTried(ctx context.Context, in *DrinkTryRequest, opts ...grpc.CallOption) (*Empty, error)
	SetDrinkMark(ctx context.Context, in *DrinkMarkRequest, opts ...grpc.CallOption) (*DrinkMarkResponse, error)
}

type drinksClient struct {
	cc grpc.ClientConnInterface
}

func NewDrinksClient(cc grpc.ClientConnInterface) DrinksClient {
	return &drinksClient{cc}
}

func (c *drinksClient) GetDrinks(ctx context.Context, in *DrinksRequest, opts ...grpc.CallOption) (*DrinksResponse, error) {
	out := new(DrinksResponse)
	err := c.cc.Invoke(ctx, "/proto.Drinks/GetDrinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinksClient) GetDrinkOfDay(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DrinkOfDayResponse, error) {
	out := new(DrinkOfDayResponse)
	err := c.cc.Invoke(ctx, "/proto.Drinks/GetDrinkOfDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinksClient) GetDrinkById(ctx context.Context, in *DrinkRequest, opts ...grpc.CallOption) (*DrinkResponse, error) {
	out := new(DrinkResponse)
	err := c.cc.Invoke(ctx, "/proto.Drinks/GetDrinkById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinksClient) SetDrinkTried(ctx context.Context, in *DrinkTryRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Drinks/SetDrinkTried", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinksClient) SetDrinkMark(ctx context.Context, in *DrinkMarkRequest, opts ...grpc.CallOption) (*DrinkMarkResponse, error) {
	out := new(DrinkMarkResponse)
	err := c.cc.Invoke(ctx, "/proto.Drinks/SetDrinkMark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrinksServer is the server API for Drinks service.
type DrinksServer interface {
	GetDrinks(context.Context, *DrinksRequest) (*DrinksResponse, error)
	GetDrinkOfDay(context.Context, *Empty) (*DrinkOfDayResponse, error)
	GetDrinkById(context.Context, *DrinkRequest) (*DrinkResponse, error)
	SetDrinkTried(context.Context, *DrinkTryRequest) (*Empty, error)
	SetDrinkMark(context.Context, *DrinkMarkRequest) (*DrinkMarkResponse, error)
}

// UnimplementedDrinksServer can be embedded to have forward compatible implementations.
type UnimplementedDrinksServer struct {
}

func (*UnimplementedDrinksServer) GetDrinks(ctx context.Context, req *DrinksRequest) (*DrinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrinks not implemented")
}
func (*UnimplementedDrinksServer) GetDrinkOfDay(ctx context.Context, req *Empty) (*DrinkOfDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrinkOfDay not implemented")
}
func (*UnimplementedDrinksServer) GetDrinkById(ctx context.Context, req *DrinkRequest) (*DrinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrinkById not implemented")
}
func (*UnimplementedDrinksServer) SetDrinkTried(ctx context.Context, req *DrinkTryRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDrinkTried not implemented")
}
func (*UnimplementedDrinksServer) SetDrinkMark(ctx context.Context, req *DrinkMarkRequest) (*DrinkMarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDrinkMark not implemented")
}

func RegisterDrinksServer(s *grpc.Server, srv DrinksServer) {
	s.RegisterService(&_Drinks_serviceDesc, srv)
}

func _Drinks_GetDrinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinksServer).GetDrinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Drinks/GetDrinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinksServer).GetDrinks(ctx, req.(*DrinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinks_GetDrinkOfDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinksServer).GetDrinkOfDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Drinks/GetDrinkOfDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinksServer).GetDrinkOfDay(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinks_GetDrinkById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinksServer).GetDrinkById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Drinks/GetDrinkById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinksServer).GetDrinkById(ctx, req.(*DrinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinks_SetDrinkTried_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrinkTryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinksServer).SetDrinkTried(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Drinks/SetDrinkTried",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinksServer).SetDrinkTried(ctx, req.(*DrinkTryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinks_SetDrinkMark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrinkMarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinksServer).SetDrinkMark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Drinks/SetDrinkMark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinksServer).SetDrinkMark(ctx, req.(*DrinkMarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Drinks_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Drinks",
	HandlerType: (*DrinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDrinks",
			Handler:    _Drinks_GetDrinks_Handler,
		},
		{
			MethodName: "GetDrinkOfDay",
			Handler:    _Drinks_GetDrinkOfDay_Handler,
		},
		{
			MethodName: "GetDrinkById",
			Handler:    _Drinks_GetDrinkById_Handler,
		},
		{
			MethodName: "SetDrinkTried",
			Handler:    _Drinks_SetDrinkTried_Handler,
		},
		{
			MethodName: "SetDrinkMark",
			Handler:    _Drinks_SetDrinkMark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drinks.proto",
}
